### ISSUE TITLE
transverse参数

### ISSUE THREAD

**Issue by Myangyang** [dogXgod/fullSlip#6]
transverse设置位false  项目编译报错
![微信截图_20190920110142](https://user-images.githubusercontent.com/29976607/65296105-0bbca300-db96-11e9-8aae-43550ef14f75.png)

**Comment by xgod1862** [comment]
找到问题了，因为用了componentDidUpdate，之前的想法是只有在transverse=true纵向的时候插件上方才可以插入其他内容，没想到transverse=false的情况，导致会重复调用setState，现在已经解决，感谢
